route:
  receiver: "default"
  group_by: ["alertname", "instance"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5m
  routes:
    - match:
        alertname: "HighCPUUsage"
      receiver: "notification"
    - match:
        alertname: "HighVMUsage"
      receiver: "recovery"

receivers:
  - name: "default"
    telegram_configs:
      - bot_token: "6876552598:AAHzA2FNVROCVyIKWEIenrVoqOREK875x3E"
        api_url: "https://api.telegram.org"
        chat_id: 993767491
        message: "Alertname: somerhing wrong"
        parse_mode: ""
        send_resolved: false
  - name: "notification"
    telegram_configs:
      - bot_token: "6876552598:AAHzA2FNVROCVyIKWEIenrVoqOREK875x3E"
        api_url: "https://api.telegram.org"
        chat_id: 993767491
        message: "Alertname: {{ .GroupLabels.alertname }}\n\n Severity: {{ .CommonLabels.severity }}\n\n Summary: {{ .CommonAnnotations.summary }}\n\n====================\n\n{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        parse_mode: ""
        send_resolved: false
  - name: "recovery"
    telegram_configs:
      - bot_token: "6876552598:AAHzA2FNVROCVyIKWEIenrVoqOREK875x3E"
        api_url: "https://api.telegram.org"
        chat_id: 993767491
        message: "Alertname: {{ .GroupLabels.alertname }}\n\n Severity: {{ .CommonLabels.severity }}\n\n Summary: {{ .CommonAnnotations.summary }}\n\n====================\n\n{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        parse_mode: ""
        send_resolved: true
