route:
  group_by: ["alertname", "instance", "severity"]
  group_wait: 15s
  group_interval: 30s
  repeat_interval: 5m
  receiver: "telegram-test"

receivers:
  - name: "telegram-test"
    telegram_configs:
      - bot_token: "6876552598:AAHzA2FNVROCVyIKWEIenrVoqOREK875x3E"
        api_url: "https://api.telegram.org"
        chat_id: 993767491
        message: "Alertname: {{ .GroupLabels.alertname }}\n\n Severity: {{ .CommonLabels.severity }}\n\n Summary: {{ .CommonAnnotations.summary }}\n\n====================\n\n{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        parse_mode: ""
        send_resolved: false
