version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitor

  nginx:
    image: axel76/mon-nginx:v02
    ports:
      - "8085:80"
    volumes:
      - nginx-logs:/var/log/nginx
    networks:
      - monitor

  apache:
    image: axel76/mon-apache:v01
    ports:
      - "8081:8081"
    networks:
      - monitor

  promtail:
    image: grafana/promtail:latest
    volumes:
      - nginx-logs:/var/log/nginx
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - monitor

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - loki-data:/loki
      - loki-wal:/wal
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - monitor

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitor

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    networks:
      - monitor


  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    command: --config.file=/etc/alertmanager/alertmanager.yml
    networks:
      - monitor

volumes:
  prometheus-data:
  grafana-storage: {}
  nginx-logs: {}
  loki-data: {}
  loki-wal: {}

networks:
  monitor:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16